---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-fights-config
  labels:
    app: rest-fights
    application: fights-service
    system: quarkus-super-heroes
data:
  QUARKUS_LIQUIBASE_MONGODB_MIGRATE_AT_START: false
  QUARKUS_MONGODB_HOSTS: fights-db:27017
  QUARKUS_STORK_HERO_SERVICE_SERVICE_DISCOVERY_TYPE: kubernetes
  QUARKUS_STORK_HERO_SERVICE_SERVICE_DISCOVERY_APPLICATION: rest-heroes
  QUARKUS_STORK_HERO_SERVICE_SERVICE_DISCOVERY_PORT_NAME: http
  QUARKUS_STORK_HERO_SERVICE_SERVICE_DISCOVERY_REFRESH_PERIOD: 1H
  QUARKUS_STORK_VILLAIN_SERVICE_SERVICE_DISCOVERY_TYPE: kubernetes
  QUARKUS_STORK_VILLAIN_SERVICE_SERVICE_DISCOVERY_APPLICATION: rest-villains
  QUARKUS_STORK_VILLAIN_SERVICE_SERVICE_DISCOVERY_REFRESH_PERIOD: 1H
  QUARKUS_STORK_VILLAIN_SERVICE_SERVICE_DISCOVERY_PORT_NAME: http
  QUARKUS_STORK_NARRATION_SERVICE_SERVICE_DISCOVERY_TYPE: kubernetes
  QUARKUS_STORK_NARRATION_SERVICE_SERVICE_DISCOVERY_APPLICATION: rest-narration
  QUARKUS_STORK_NARRATION_SERVICE_SERVICE_DISCOVERY_REFRESH_PERIOD: 1H
  QUARKUS_STORK_NARRATION_SERVICE_SERVICE_DISCOVERY_PORT_NAME: http
  QUARKUS_GRPC_CLIENTS_LOCATIONS_HOST: grpc-locations
  QUARKUS_GRPC_CLIENTS_LOCATIONS_PORT: 80
  QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
  KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
  MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8080/apis/registry/v2
